### ISSUE TITLE
[Query]: how to convert the (collection.+environment) files together into a JMX 

### ISSUE THREAD

**Issue by Venkata-Maddineni** [sercheo87/convert-postman-jmeter#11]
Steps: 
1.Create a postman collection suite  with multiple API's and it has separate environment details JSON file.
2.I have exported both of them from postman.

and i know how to convert to JMX without environment JSON..!

Could you please share steps/commands that  how to generate JMX with combination of  collection.+environment ?

**Comment by sercheo87** [comment]
Actually not support environment and JMX on JMeter this tool.

But on next version add support to environment files.

With the generation JMX please put provider JMX for develop template generation.
