### ISSUE TITLE
Unable to convert collection and env on Mac M2

### ISSUE THREAD

**Issue by ale-sanchez-g** [sercheo87/convert-postman-jmeter#139]
**Describe the bug**
Currently, when I run the command to convert a Postman collection with an environment file I get an error message

```bash
WARNING: package sun.awt.X11 not in java.desktop
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
```

**To Reproduce**

```bash
npm i convert-postman-jmeter -g
convert-postman-jmeter -p tes/postman_collection.json -j jmeter/jmeter_collection.jmx -e test/postman_environment.json
```
ERROR
WARNING: package sun.awt.X11 not in java.desktop

**Expected behavior**

**Screenshots**
<img width="663" alt="image" src="https://github.com/sercheo87/convert-postman-jmeter/assets/8701973/0bac497a-a9af-4f5a-9397-7d6cc5ccc6c6">
<img width="715" alt="image" src="https://github.com/sercheo87/convert-postman-jmeter/assets/8701973/7e7069a5-1905-4306-9f78-427821af4d24">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.0
- "convert-postman-jmeter": "^2.3.0",
- NODE: v20.1.0

**Comment by AntonioSun** [comment]
what you get in your `jmeter_collection.jmx` file please?

**Comment by sercheo87** [comment]
Hi, at the moment it is not possible to verify this error, because I don't have a MacBook with M2 to check the error.

Sorry, I hope that in the future I can validate this scenario.
