### ISSUE TITLE
Error reading template file:  templates/jmeter-template.xml Error: ENOENT: no such file or directory, open 'templates/jmeter-template.xml'

### ISSUE THREAD

**Issue by lineuman** [sercheo87/convert-postman-jmeter#73]
windows 10
npm 6.14.8

  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'templates/jmeter-template.xml'

**Comment by sercheo87** [comment]
Fix on [2.0.18](https://www.npmjs.com/package/convert-postman-jmeter)
