### ISSUE TITLE
sercheo87, could you cut a new release for npmjs?

### ISSUE THREAD

**Issue by tamusjroyce** [sercheo87/convert-postman-jmeter#94]
Hi sercheo87!

The new changes that support Collection ItemGroup.item -> [ item, item, ...] works great in the repository.

I did notice `env.values.forEach(function (variable) {` should be `(env.values || []).forEach(function (variable) {` or `env.values?.forEach(function (variable) {`

Otherwise, you have to use the -e env-opts.json that holds `{ "values": [] }`.

Looking great and thank you for the great app! happy coding!
-TamusJRoyce

**Comment by tamusjroyce** [comment]
Also noticed that `dataPostman.info.nam.replaceAll(" ", "_")` could be `(dataPostman.info.name || "").split(" ").join("_")` for a little better compatibility with older versions of node.

**Comment by tamusjroyce** [comment]
Feel free to close with no cut. Seems like what is in master is currently unstable. Glad to see active development.

![image](https://user-images.githubusercontent.com/6413071/206124569-bb87a85e-b0bd-486f-9331-cd421bc63e7b.png)

**Comment by tamusjroyce** [comment]
0de12917af9f846e8875c25c731bd7f301749391 is good. bisect shows issue above after that

**Comment by sercheo87** [comment]
The code was fixed, with support of environment file postman.
